<?php

return [
    'documents.view' => 'Voir et télécharger les documents dans les dossiers accessibles.',
    'documents.view-hierarchique' => 'Voir aussi les documents et dossiers des collègues de la même structure ou des structures dont vous êtes responsable (vue organisationnelle).',
    'documents.create' => 'Déposer de nouveaux documents dans les dossiers.',
    'documents.edit' => 'Modifier les métadonnées des documents existants.',
    'documents.delete' => 'Supprimer ou archiver des documents.',
    'types-documents.view' => 'Consulter la liste des types de documents (PDF, Word, etc.). Menu réservé à l’admin par défaut.',
    'types-documents.create' => 'Créer de nouveaux types de documents.',
    'types-documents.edit' => 'Modifier les types de documents existants.',
    'types-documents.delete' => 'Supprimer des types de documents.',
    'recherche.view' => 'Accéder au menu Recherche (documents / dossiers). Réservé à l’admin par défaut.',
    'corbeille.view' => 'Accéder au menu Corbeille et restaurer des documents. Réservé à l’admin par défaut.',
    'dossiers.view' => 'Voir la liste et le contenu des dossiers accessibles.',
    'dossiers.create' => 'Créer des dossiers dans son espace personnel « Mes dossiers » (racine auto à la connexion).',
    'dossiers.edit' => 'Modifier les dossiers existants (nom, description, etc.).',
    'dossiers.delete' => 'Supprimer des dossiers.',
    'dossiers.view-confidentiel' => 'Accéder aux dossiers marqués comme confidentiels.',
    'dossiers.create-structure' => 'Créer des dossiers dans le plan de classement des structures autorisées.',
    'dossiers.create-racine-structure' => 'Créer un dossier racine rattaché à une structure (direction / service).',
    'utilisateurs.view' => 'Consulter la liste des utilisateurs et leurs profils.',
    'utilisateurs.create' => 'Créer de nouveaux comptes utilisateur.',
    'utilisateurs.edit' => 'Modifier les utilisateurs (profil, rôle, 2FA, etc.).',
    'utilisateurs.delete' => 'Supprimer des comptes utilisateur.',
    'courriers.view' => 'Consulter les courriers arrivée et départ accessibles (registre, fiche, pièces jointes).',
    'courriers.create' => 'Enregistrer un nouveau courrier (scan arrivée externe, départ interne, etc.).',
    'courriers.edit' => 'Modifier un courrier en cours de traitement au secrétariat (métadonnées, parapheur).',
    'courriers.orienter' => 'Orienter un courrier arrivée vers une structure ou un responsable.',
    'courriers.ventiler' => 'Ventiler un courrier arrivée vers des destinataires internes.',
    'courriers.signer' => 'Signer un courrier départ transmis au directeur.',
    'courriers.rejeter' => 'Rejeter un courrier départ en attente de signature.',
    'courriers.transmettre' => 'Transmettre ou expédier un courrier (directeur, secrétariat destinataire, etc.).',
    'courriers.archiver' => 'Archiver un courrier en fin de circuit ou après traitement.',
    'courriers.recevoir' => 'Accepter ou refuser la réception d’un courrier départ interne adressé à sa structure.',
    'suivi-paiements.view' => 'Consulter et exporter les fiches de suivi des paiements (FSP FACTURE / FSP MAD).',
];
